spring:
  application:
    name: msj-product
  datasource:
    url: jdbc:mysql://localhost:3306/meishijia?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: msj-product
server:
  port: 9103